name: Main

on:
  push:
  pull_request:
    types: [opened]

env:
    KOSLI_FLOW: sonarcloud_CLI_test
    KOSLI_TRAIL: ${{ github.sha }}
    KOSLI_HOST: https://staging.app.kosli.com
    KOSLI_ORG: FayeSGW
    KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
    KOSLI_SONAR_API_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: 2.10.15

      - name: Attest SonarCloud results to Kosli
        run:
          kosli attest sonar \
            --dry-run \
            --name=sonar-attest
